<?php

return [

    'motivational' => [
        'If you want something you’ve never had, you must be willing to do something you’ve never done.',
        'Strength does not come from physical capacity. It comes from an indomitable will.”',
        'Your body can stand almost anything. It’s your mind that you have to convince.',
        'Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.',
        'I don’t count my sit-ups. I only start counting when it starts hurting because they’re the only ones that count.',
        'Your health account, your bank account, they’re the same thing. The more you put in, the more you can take out.',
        'Your body can stand almost anything. It’s your mind that you have to convince.',
        'There are two types of pain in this world: pain that hurts you, and pain that changes you.',
        'Ability is what you’re capable of doing. Motivation determines what you do. Attitude determines how well you do it.',
        'I hated every minute of training, but I said, ‘Don’t quit. Suffer now and live the rest of your life as a champion.',
        'To keep the body in good health is a duty… otherwise we shall not be able to keep our mind strong and clear.',
        'Things may come to those who wait, but only the things left by those who hustle.',
        'If something stands between you and your success, move it. Never be denied.',
        'If you want something you’ve never had, you must be willing to do something you’ve never done.',
        'You have to think it before you can do it. The mind is what makes it all possible.',
        'Things work out best for those who make the best of how things work out.',
        'Success is walking from failure to failure with no loss of enthusiasm.',
        'The mind is the most important part of achieving any fitness goal. Mental change always comes before physical change.',
        'Your body can stand almost anything. It’s your mind that you have to convince.',
        'Beast is what I become each and every time I step through those gym doors.',
        'My body is under construction, I am the architect of my own destiny.',
        'Never say the sky’s the limit when there are footprints on the moon.',
        'If you want something you never had, you have to do something you’ve never done.',
        'If exercise was pill, It would be the most powerful medication know to humans.',
        'Definition of really good workout: when you hate doing it, But you love finishing it.',
        'Your body can stand almost anything, It’s your mind that you have to convince.',
        'I am not telling you it is going to be easy, I am telling It’s going to be worth it.',
        'When things don’t happen right away just remember, it takes 6 months to build a rolls-royce and 13 hours to build toyota.',
        'You can never expect to success, if you only put in work on the days you feel like it.',
        'Exercise is celebration of what your body can do, not punishment what you ate.',
        'While losers hit the snooze button and go back to dreamland, winners stand up and work on their dreams.',
        'While losers hit the snooze button and go back to dreamland, winners stand up and work on their dreams.',
        'While losers always choose the easy way, winners always choose the right one.',
        'It may seem like every day is getting harder, but every day you’re getting stronger.',
        'The difference between your body this week and next week is what you do for the next seven days to achieve your goal.',
        'Get out of your comfort zone and you will never be the same again.',
        'The hard part isn’t getting your body in shape. The hard part is getting your mind in shape.',
        'As long as you keep going, you will never fail. Refuse any other outcome but the one you are aiming for.',
    ],

];
